name: Python Package CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version override (leave empty to use matrix)'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]
        exclude:
          - python-version: 3.1  # Explicitly exclude 3.1 if it somehow gets included
      fail-fast: false

    # Skip the job if Python 3.1 is specified anywhere
    if: |
      !contains(matrix.python-version, '3.1') && 
      !contains(github.event.inputs.python-version, '3.1')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ inputs.python-version || matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version || matrix.python-version }}
          # Explicitly add an error for Python 3.1
          # This ensures the job fails early with a clear message if 3.1 somehow gets through
          check-latest: ${{ !(inputs.python-version == '3.1' || matrix.python-version == '3.1') }}

      - name: Check Python version
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest

      - name: Run tests
        run: pytest